BEGIN;
--
-- Add field actors to movie
--
CREATE TABLE "play" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "movie_id" bigint NOT NULL, 
    "person_id" bigint NOT NULL,
    "role" varchar(150)
);
--
-- Alter field director on movie
--
-- (no-op)
ALTER TABLE "play" ADD CONSTRAINT "play_movie_id_person_id_0c405d42_uniq" UNIQUE ("movie_id", "person_id");
ALTER TABLE "play" ADD CONSTRAINT "play_movie_id_b073e9b8_fk_movie_id" FOREIGN KEY ("movie_id") REFERENCES "movie" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "play" ADD CONSTRAINT "play_person_id_23ae9fa8_fk_person_id" FOREIGN KEY ("person_id") REFERENCES "person" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "play_movie_id_b073e9b8" ON "play" ("movie_id");
CREATE INDEX "play_person_id_23ae9fa8" ON "play" ("person_id");
COMMIT;
