BEGIN;
--
-- Create model Person
--
CREATE TABLE "person" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL, "birthdate" date NULL);
--
-- Create model Movie
--
CREATE TABLE "movie" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(300) NOT NULL, "release_year" integer NOT NULL, "duration" integer NULL, "color" varchar(15) NULL, "pg" varchar(5) NULL, "poster_uri" varchar(200) NULL, "synopsis" text NULL, "director_id" bigint NULL);
ALTER TABLE "movie" ADD CONSTRAINT "movie_director_id_a1a23574_fk_person_id" FOREIGN KEY ("director_id") REFERENCES "person" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "movie_director_id_a1a23574" ON "movie" ("director_id");
COMMIT;
