# Generated by Django 4.2.16 on 2024-09-10 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('movies', '0001_initial'), ('movies', '0002_movie_color_movie_pg_movie_poster_uri_movie_synopsys'), ('movies', '0003_person'), ('movies', '0004_movie_director')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthdate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.IntegerField(db_column='release_year')),
                ('duration', models.IntegerField(null=True)),
                ('color', models.CharField(choices=[('COLOR', 'Color'), ('BLACK_AND_WHITE', 'Black And White')], max_length=15, null=True)),
                ('pg', models.CharField(choices=[('G', 'G'), ('PG', 'Pg'), ('PG-13', 'Pg 13'), ('R', 'R'), ('NC-17', 'Nc 17')], max_length=5, null=True)),
                ('poster_uri', models.URLField(null=True)),
                ('synopsys', models.TextField(null=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
