# Generated by Django 4.2.16 on 2024-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('year', models.IntegerField(db_column='release_year')),
                ('duration', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
