# Generated by Django 4.2.16 on 2024-09-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='color',
            field=models.CharField(choices=[('COLOR', 'Color'), ('BLACK_AND_WHITE', 'Black And White')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='pg',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'Pg'), ('PG-13', 'Pg 13'), ('R', 'R'), ('NC-17', 'Nc 17')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_uri',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsys',
            field=models.TextField(null=True),
        ),
    ]
