# Generated by Django 4.2.16 on 2024-09-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_color_movie_pg_movie_poster_uri_movie_synopsys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthdate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
