# Generated by Django 4.2.16 on 2024-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_actors_alter_movie_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='synopsys',
            new_name='synopsis',
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(db_table='play', related_name='played_movies', to='movies.person'),
        ),
    ]
