BEGIN;
--
-- Create model Movie
--
CREATE TABLE "movie" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "title" varchar(300) NOT NULL, 
    "release_year" integer NOT NULL, 
    "duration" integer NULL, 
    "pg" varchar(5) NULL, 
    "synopsis" text NULL, 
    "poster_uri" varchar(200) NULL, 
    "color" varchar(15) NULL
);
--
-- Create model Person
--
CREATE TABLE "person" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "name" varchar(150) NOT NULL, 
    "birthdate" date NULL
;
--
-- Create model Play
--
CREATE TABLE "play" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "role" varchar(150) NULL, 
    "actor_id" bigint NOT NULL, 
    "movie_id" bigint NOT NULL
);
--
-- Add field actors to movie
--
-- (no-op)
--
-- Add field director to movie
--
ALTER TABLE "movie" ADD COLUMN "director_id" bigint NULL CONSTRAINT "movie_director_id_a1a23574_fk_person_id" REFERENCES "person"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "movie_director_id_a1a23574_fk_person_id" IMMEDIATE;
ALTER TABLE "play" ADD CONSTRAINT "play_actor_id_39199b6a_fk_person_id" FOREIGN KEY ("actor_id") REFERENCES "person" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "play" ADD CONSTRAINT "play_movie_id_b073e9b8_fk_movie_id" FOREIGN KEY ("movie_id") REFERENCES "movie" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "play_actor_id_39199b6a" ON "play" ("actor_id");
CREATE INDEX "play_movie_id_b073e9b8" ON "play" ("movie_id");
CREATE INDEX "movie_director_id_a1a23574" ON "movie" ("director_id");
COMMIT;
